### ISSUE TITLE
Unknown plugin 'add-module-exports' from bundler in react-native

### ISSUE THREAD

**Issue by bobbybeckner** [fabiospampinato/overstated#1]
Getting, "Unknown plugin 'add-module-exports'" from the bundler in react-native.

```
error: bundling failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/deep-object-diff/package.json" at 0, attempted to resolve relative to "/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/deep-object-diff"
    at /Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transform (/Users/pixelbobby/_dev/LL/ll-mobile-ignite2/node_modules/metro/src/transformer.js:135:5)
```

**Comment by fabiospampinato** [comment]
It looks like `unstated-debug` uses `deep-object-diff` which in turns has this in its `package.json`:

```
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ],
    "plugins": [
      "add-module-exports",
      "transform-es2015-modules-umd",
      "babel-jest-assertions",
      "gwt"
    ]
  },
```

Maybe your bundler is trying to recompile `deep-object-diff` for some reason?

**Comment by bobbybeckner** [comment]
Got it.  Yeah, it looks like it's actually an issue with the `deep-object-diff` library and the `babel` reference possibly being outdated.

As a short-term solution, I attempted to use the `combine` method from `unstated-enhancers` yet ran into the same issue.

https://github.com/xaamin/unstated-enhancers

p.s.  Thanks for the awesome contributions to Unstated!

**Comment by fabiospampinato** [comment]
If you only need the `combine` method maybe you should use the plugins included into `overstated` individually: https://github.com/fabiospampinato/unstated-compose.

I'm closing this then since it seems the problem doesn't originate from overstated.
